<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>css</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="css/main.css">
	<link rel="stylesheet" href="css/animate.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
	<link rel="stylesheet" href="libs/bootstrap/css/bootstrap.min.css">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

</head>
<body>


	<nav class="top_nav">
		<nav class="navbar navbar-default menu">
		  <div class="container">
   			 <!-- Brand and toggle get grouped for better mobile display -->
   				 <div class="navbar-header">
     				 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        				  <span class="sr-only">Toggle navigation</span>
      					  <span class="icon-bar"></span>
       					   <span class="icon-bar"></span>
      					  <span class="icon-bar"></span>
      				</button>
     		 <div><a href=""><img src="images/logo.png" class="img-responsive" alt=""></a></div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li ><a href="#">About</a></li>
        <li class="active-link"><a href="#">Gallery</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">Contact</a></li>
          </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
	</nav>


	<section class="header_wrap">
		<div class="container">
			<div class="bg"><img src="images/banner.png" width="1140px" height="553px" alt=""></div>
			<div class="text"><h2>free<br/>template</h2></div>

		</div>
	</section>


	<section class="first_section" id="animate1">
		<div class="container">
		<div class="row">
			<div class="first_section_text col-lg-4 post">
				<h2>Hinc nobis<br/>duo ut</h2>
				<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores </p>
				 <a href="#" class="more">Read more...</a>
				<p class="hidden">eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
			</div>
			<div class="first_section_image col-lg-8 post last">
				<p class="date text_right">07/08</p>
				<img src="images/img_1.png" class="img-responsive" alt="">
			</div>
		</div>
		</div>
	</section>




		<section class="second_section">
		<div class="container">
			<div class="flex_row">
				<div class="column_left" id="animate2">
					<p class="date text_left post">28/07</p>
					<div class="img post"><img src="images/img_2.png" class="img-responsive" alt=""></div>
					<div class="text post"><h2>Eos no <br>
					liber <br>
					iudicabit.</h2></div>
				</div>

				<div class="column_right" id="animate3">
					<div class="text post">
						<h2 class="text_right">Ea eum cibot<br/><span>graece<span></h2>
						<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
						 <a href="#" class="more">Read more...</a>
						<p class="hidden">eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
					</div>

					<div class="img post">
					<p class="date text_right post">15/07</p>
					<img src="images/img_3.png" class="img-responsive" alt=""></div>
				</div>
				</div>
		</div>
	</section>
	
	<section class="third_section" id="animate4">
	<div class="container">
		<div class="third_section__bg post">
			<img src="images/img_4.png" alt="">
		</div>
		<div class="text post">
			<div class="title_block"><h2>SIGN UP FOR NEWSLETTER</h2></div>
			<button class="btn">sign up</button>
		</div>
	</div>
	</section>

	<section class="fourth_section" id="animate4">
		<div class="container">
			<div class="menu_items post">
				<div class="item"><a href="#">vitae   </a></div>
				<div class="item">-</div>
				<div class="item"><a href="#">audiam   </a></div>
				<div class="item">-</div>
				<div class="item"><a href="#">dicam   </a></div>
				<div class="item">-</div>
				<div class="item"><a href="#">inermis   </a></div>
			</div>
			<div class="text post">
				<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione <br> voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, <br>
				consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
			</div>
		</div>
	</section>

	<section class="fifth_section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="column .col-xl-4 col-md-4 col-sm-4 col-xs-4"><img src="images/img_col_1.png" class="img-responsive" alt=""><div class="text"><h2>mei</h2></div></div>
				
				<div class="column .col-xl-4 col-md-4 col-sm-4 col-xs-4"><img src="images/img_col_2.png" class="img-responsive" alt=""><div class="text"><h2>cibo</h2></div></div>
				<div class="column .col-xl-4 col-md-4 col-sm-4 col-xs-4"><img src="images/img_col_3.png" class="img-responsive" alt=""><div class="text"><h2>eum</h2></div></div>
				
			</div>
		</div>
	</section>


	<section class="sixth_section">
		<div class="container">
		<div class="flex_row">
			<div class="column_left post">
				<div class="image"><img src="images/img_5.png" class="img-responsive" alt=""></div>
			</div>
			<div class="column_right">

			<div class="text">
						<h2 class="text_right">Pri att mediocrem<br/><span> corrumpit<span></h2>
						<p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
						 <a href="#" class="more">Read more...</a>
						<p class="hidden">eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.</p>
					</div>

			</div>
		</div>
		</div>
	</section>


	<footer>
		<div class="container">
			<div class="menu_items">
				<div class="item"><a href="#">about</a></div>
				<div class="item">-</div>
				<div class="item"><a href="#">terms and condition</a></div>
				<div class="item">-</div>
				<div class="item"><a href="#">symu freebies</a></div>
				<div class="item">-</div>
				<div class="item"><a href="#">contact us</a></div>
			</div>
			<div class="text"><p>This tempalte is free to use for personal or commercial projects, attribution is appreciated but not required. <br>
			If you have any additional questions that may not have been answered above, please don't hesitate to contact us at contact@symu.co</p></div>
			
			<ul class="social">
				<li><a href="" class="fa fa-2x fa-facebook-official"></a></li>
				<li><a href="" class="fa fa-2x fa-twitter-square"></a></li>
				<li><a href="" class="fa fa-2x fa-youtube-square"></a></li>
				<li><a href="" class=" fa fa-2x fa-dribbble"></a></li>
				<li><a href="" class=" fa fa-2x fa-instagram"></a></li>
			</ul>
		</div>
	</footer>




<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
		<script type="text/javascript" src="js/script.js"></script>
<script src="libs/bootstrap/js/bootstrap.min.js"></script>


</body>
</html>
